FROM willhallonline/ansible:2.13-alpine-3.16

RUN apk update && \
	apk add --no-cache sshpass && \
	ansible-galaxy install ansistrano.deploy ansistrano.rollback && \
	rm -rf /tmp/* && \
	rm -rf /var/cache/apk/*